version: '3'
services:
 vault-server:
  image: vault:latest
  ports:
  - "8200:8200"
  environment:
   - VAULT_ADDR=http://localhost:8200
   - VAULT_DEV_ROOT_TOKEN_ID=contra
  cap_add:
  - IPC_LOCK
  healthcheck:
   test: "exit 0"
 vault-client:
  #image: estefaniia04/miimagenvault:latest
  container_name: myvault
  build: .
  environment:
   - VAULT_ADDR=http://vault-server:8200
   - VAULT_TOKEN=contra
  depends_on:
   vault-server:
    condition: service_healthy
  



