version: '3'
services:
 vault-server:
  image: vault:latest
  ports:
  - "8200:8200"
  environment:
   - VAULT_ADDR=http://localhost:8200 #IP en la que se montará la imagen, en esta dirección se abrirá la UI de vault.
   - VAULT_DEV_ROOT_TOKEN_ID=contra #Contraseña que utilizará el cliente
  cap_add:
  - IPC_LOCK
  healthcheck:
   test: "exit 0"
 vault-client:
  #image: estefaniia04/miimagenvault:latest #Descomentar en caso de querer comprobar el funcionamiento de la imagen descargada desde el repositorio publico de Docker Hub https://hub.docker.com/r/estefaniia04/miimagenvault  
  container_name: myvault
  build: .
  environment:
   - VAULT_ADDR=http://vault-server:8200
   - VAULT_TOKEN=contra
  depends_on:
   vault-server:
    condition: service_healthy
  
